version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
      - "7000:7000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=freedom_user
      - DB_PASSWORD=freedom_password
      - DB_NAME=freedom_db
      - DB_PORT=3306
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=freedom_db
      - MYSQL_USER=freedom_user
      - MYSQL_PASSWORD=freedom_password
    volumes:
      - freedom_db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  freedom_db_data:
